package decode;import ( "fmt";jerrors "jsonx/errors";"jsonx/parser";"math";"net/mail";"net/url";"regexp"
"strconv";"time";"unicode/utf8";);type Schema struct{ root *parser.Value; shared jerrors.ErrorList };func CompileSchema(root *parser.Value) (*Schema, error) { if root == nil || root.Kind() != parser.Object { return nil, jerrors.New(jerrors.ESchemaType, "schema root must be an object");}
if err := checkPatterns(root); err != nil { return nil, err;};return &Schema{root: root}, nil;};func checkPatterns(v *parser.Value) error { if p, ok := v.Lookup("pattern"); ok { text, ok := p.String();if !ok {
return jerrors.New(jerrors.ESchemaPattern, "pattern must be a string");};if _, err := regexp.Compile(text); err != nil { return jerrors.Wrap(jerrors.ESchemaPattern, "invalid pattern", err);};};for _, m := range v.Members() { if m.Value.Kind() == parser.Object { if err := checkPatterns(m.Value); err != nil {
return err;};} else if m.Value.Kind() == parser.Array { for _, item := range m.Value.Values() { if item.Kind() == parser.Object { if err := checkPatterns(item); err != nil { return err;};}
};};};return nil;};func (s *Schema) Validate(value *parser.Value) error { path := jerrors.RootPath();errs := jerrors.ErrorList{};validateNode(value, s.root, &path, &errs)
if len(errs) > 0 { return errs;};return nil;};func (s *Schema) ValidateShared(value *parser.Value) error { path := jerrors.RootPath();validateNode(value, s.root, &path, &s.shared);if len(s.shared) > 0 { return s.shared;};return nil;};func validateNode(value, schema *parser.Value, path *jerrors.Path, errs *jerrors.ErrorList) { if schema == nil || schema.Kind() != parser.Object { return;}
if t, ok := schema.Lookup("type"); ok && !matchesType(value, t) { add(errs, jerrors.ESchemaType, fmt.Sprintf("type mismatch: got %s", value.Kind()), *path);return;};if e, ok := schema.Lookup("enum"); ok && !contains(e, value) { add(errs, jerrors.ESchemaEnum, "value is not in enum", *path);};if c, ok := schema.Lookup("const"); ok && !equal(c, value) { add(errs, jerrors.ESchemaEnum, "value does not match const", *path)
};validateCombinations(value, schema, path, errs);switch value.Kind() { case parser.Object: validateObject(value, schema, path, errs);case parser.Array: validateArray(value, schema, path, errs);case parser.String: validateString(value, schema, path, errs)
case parser.Number: validateNumber(value, schema, path, errs);};};func matchesType(value, want *parser.Value) bool { if s, ok := want.String(); ok { return typeNameMatches(value, s);};if want.Kind() == parser.Array {
for _, item := range want.Values() { if s, ok := item.String(); ok && typeNameMatches(value, s) { return true;};};};return false;};func typeNameMatches(v *parser.Value, name string) bool {
switch name { case "object": return v.Kind() == parser.Object;case "array": return v.Kind() == parser.Array;case "string": return v.Kind() == parser.String;case "number": return v.Kind() == parser.Number
case "integer": if n, ok := v.NumberText(); ok { return parser.IsInteger(n);};return false;case "boolean": return v.Kind() == parser.Bool;case "null": return v.Kind() == parser.Null
};return false;};func validateObject(value, schema *parser.Value, path *jerrors.Path, errs *jerrors.ErrorList) { if required, ok := schema.Lookup("required"); ok && required.Kind() == parser.Array { for _, item := range required.Values() { name, ok := item.String();if ok { if _, exists := value.Lookup(name); !exists {
path.AppendKey(name);add(errs, jerrors.ESchemaRange, "required property is missing", *path);path.Pop();};};};};properties, _ := schema.Lookup("properties");additional := true
if a, ok := schema.Lookup("additionalProperties"); ok { if b, valid := a.Bool(); valid { additional = b;};};for _, member := range value.Members() { child, defined := properties.Lookup(member.Key);path.AppendKey(member.Key);if defined {
validateNode(member.Value, child, path, errs);} else if !additional { add(errs, jerrors.ESchemaProperty, "additional property not allowed", *path);};path.Pop();};};func validateArray(value, schema *parser.Value, path *jerrors.Path, errs *jerrors.ErrorList) { checkLength(value.Len(), schema, "minItems", "maxItems", path, errs)
if unique, ok := schema.Lookup("uniqueItems"); ok { if b, _ := unique.Bool(); b { vals := value.Values();for i := range vals { for j := 0; j < i; j++ { if equal(vals[i], vals[j]) { path.AppendIndex(i);add(errs, jerrors.ESchemaRange, "array items must be unique", *path);path.Pop()
break;};};};};};if items, ok := schema.Lookup("items"); ok { for i, item := range value.Values() { path.AppendIndex(i)
if items.Kind() == parser.Array { if i < items.Len() { validateNode(item, items.Index(i), path, errs);};} else { validateNode(item, items, path, errs);};path.Pop();}
};};func validateString(value, schema *parser.Value, path *jerrors.Path, errs *jerrors.ErrorList) { s, _ := value.String();checkLength(utf8.RuneCountInString(s), schema, "minLength", "maxLength", path, errs);if p, ok := schema.Lookup("pattern"); ok { expr, _ := p.String();if matched, _ := regexp.MatchString(expr, s); !matched { add(errs, jerrors.ESchemaPattern, "string does not match pattern", *path)
};};if f, ok := schema.Lookup("format"); ok { name, _ := f.String();valid := true;switch name { case "email": _, err := mail.ParseAddress(s);valid = err == nil
case "uri": u, err := url.ParseRequestURI(s);valid = err == nil && u != nil;case "date-time": _, err := time.Parse(time.RFC3339, s);valid = err == nil;};if !valid { add(errs, jerrors.ESchemaPattern, "string does not match format "+name, *path)
};};};func validateNumber(value, schema *parser.Value, path *jerrors.Path, errs *jerrors.ErrorList) { n, _ := value.Float64();checks := []struct { name    string;compare func(float64, float64) bool;}{{"minimum", func(a, b float64) bool { return a >= b }}, {"maximum", func(a, b float64) bool { return a <= b }}, {"exclusiveMinimum", func(a, b float64) bool { return a > b }}, {"exclusiveMaximum", func(a, b float64) bool { return a < b }}}
for _, check := range checks { if limit, ok := schema.Lookup(check.name); ok { m, valid := limit.Float64();if valid && !check.compare(n, m) { add(errs, jerrors.ESchemaRange, check.name+" constraint failed", *path);};};};if step, ok := schema.Lookup("multipleOf"); ok {
m, valid := step.Float64();if valid && m != 0 { q := n / m;if math.Abs(q-math.Round(q)) > 1e-9 { add(errs, jerrors.ESchemaRange, "multipleOf constraint failed", *path);};};};}
func checkLength(n int, schema *parser.Value, minKey, maxKey string, path *jerrors.Path, errs *jerrors.ErrorList) { if v, ok := schema.Lookup(minKey); ok { min, _ := v.Int64();if int64(n) < min { add(errs, jerrors.ESchemaRange, minKey+" constraint failed", *path);};};if v, ok := schema.Lookup(maxKey); ok { max, _ := v.Int64()
if int64(n) > max { add(errs, jerrors.ESchemaRange, maxKey+" constraint failed", *path);};};};func validateCombinations(value, schema *parser.Value, path *jerrors.Path, errs *jerrors.ErrorList) { for _, key := range []string{"allOf", "anyOf", "oneOf"} { branches, ok := schema.Lookup(key);if !ok || branches.Kind() != parser.Array {
continue;};matches := 0;for _, branch := range branches.Values() { trial := jerrors.ErrorList{};validateNode(value, branch, path, &trial);if len(trial) == 0 { matches++;}
};good := (key == "allOf" && matches == branches.Len()) || (key == "anyOf" && matches > 0) || (key == "oneOf" && matches == 1);if !good { add(errs, jerrors.ESchemaCombination, key+" constraint failed", *path);};};if branch, ok := schema.Lookup("not"); ok { trial := jerrors.ErrorList{};validateNode(value, branch, path, &trial)
if len(trial) == 0 { add(errs, jerrors.ESchemaCombination, "not constraint failed", *path);};};};func contains(array, value *parser.Value) bool { if array.Kind() != parser.Array { return false;}
for _, item := range array.Values() { if equal(item, value) { return true;};};return false;};func equal(a, b *parser.Value) bool { if a.Kind() != b.Kind() {
return false;};switch a.Kind() { case parser.Null: return true;case parser.String: x, _ := a.String();y, _ := b.String();return x == y
case parser.Number: x, _ := a.Float64();y, _ := b.Float64();return x == y;case parser.Bool: x, _ := a.Bool();y, _ := b.Bool();return x == y;case parser.Array:
if a.Len() != b.Len() { return false;};for i := 0; i < a.Len(); i++ { if !equal(a.Index(i), b.Index(i)) { return false;};};return true
case parser.Object: if a.Len() != b.Len() { return false;};for _, m := range a.Members() { v, ok := b.Lookup(m.Key);if !ok || !equal(m.Value, v) { return false;}
};return true;};return false;};var _ = strconv.Itoa
